model:
  name: "ResNet50"               # Name of the model
  pretrained: true               # Use pre-trained weights
  num_classes: 2                 # Number of classes in the dataset

training:
  batch_size: 32                 # Batch size
  learning_rate: 0.001           # Learning rate
  num_epochs: 25                 # Number of training epochs
  optimizer: "adam"              # Optimizer to use
  loss_function: "cross_entropy" # Loss function

data:
  data_csv: "./data/dataset.csv" # Path to the CSV file with image paths and labels
  root_dir: "./data/images"      # Root directory containing the images
  train_split: 0.7               # Percentage of data used for training (70%)
  val_split: 0.2                 # Percentage of data used for validation (20%)
  input_size: 224                # Input image size (224x224)
  batch_size: 128                # Batch size for data loading
  num_workers: 4                 # Number of workers for the DataLoader

logging:
  log_dir: "./logs"              # Directory to save logs
  log_level: "INFO"              # Logging level (INFO, DEBUG, etc.)