model:
  name: "ResNet50"               # Name of the model
  pretrained: true               # Use pre-trained weights
  num_classes: 7                 # Number of classes in the dataset

training:
  batch_size: 128                # Batch size
  learning_rate: 0.001           # Learning rate
  num_epochs: 25                 # Number of training epochs
  optimizer: "adam"              # Optimizer to use
  loss_function: "cross_entropy" # Loss function

data:
  data_csv: "./data/dataset.csv" # Path to the CSV file with image paths and labels
  root_dir: "./data/images"      # Root directory containing the images
  train_split: 0.7               # Percentage of data used for training (70%)
  val_split: 0.2                 # Percentage of data used for validation (20%)
  image_size: [224, 224]         # Input image size (224x224)
  num_workers: 4                 # Number of workers for the DataLoader
  file_path: "/home/ubuntu/projects/fairface/dataset/output/processed_images/"
  file_name: "fairface-processed_images.zip"
  input_dir: "path/to/input/images"
  output_dir: "path/to/output/images"

logging:
  log_dir: "logs"              # Directory to save logs
  log_level: "INFO"              # Logging level (INFO, DEBUG, etc.)
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  log_bucket_file: "bucket.log"
  log_preprocessing_file: "preprocessing.log"
  log_version_file: "version.log"

bucket:
  bucket_name: "dataset-fairface"                       # Bucket Name
  object_name: "dataset/fairface-processed_images.zip"  # Bucket Object
  access_key: ""                                        # Bucket Access Key
  secret_access_key: ""                                 # Bucket Secret Access Key