bucket:
  bucket_client: s3
  bucket_name: dataset-fairface
  bucket_path_file: data/raw/bucket/
  function: download
  object_file_name: fairface_original_images.zip
data:
  dataset_file: data/raw/fairface/labels.csv
  dataset_image_input_path: data/test_images
  dataset_image_output_path: data/test_output
image:
  image_mean:
  - 0.485
  - 0.456
  - 0.406
  image_size:
  - 224
  - 224
  image_std:
  - 0.229
  - 0.224
  - 0.225
logging:
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  log_bucket_file: bucket.log
  log_dir: outputs/logs
  log_evaluation_file: evaluation.log
  log_face_data_file: face_data.log
  log_level: INFO
  log_preprocessing_file: preprocessing.log
  log_training_file: training.log
  log_version_file: version.log
model:
  dropout: 0.5
  name: LResNet50E_IR
  num_classes: 7
  pretrained: true
preprocessing:
  num_rotations: 8
  num_workers: 4
  processing_type: detect_adjust_image
  rotate_angle: 45
training:
  batch_size: 128
  learning_rate: 0.001
  loss_function: cross_entropy
  num_epochs: 25
  num_workers: 4
  optimizer: adamw
  random_state: 42
  scheduler: onecyclelr
  test_size: 0.2
