data:
  dataset_image_input_path: data/test_multi_faces
  dataset_image_output_path: data/test_multi_output
image:
  image_size:
  - 224
  - 224
logging:
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  log_dir: outputs/logs
  log_level: INFO
  log_preprocessing_file: preprocessing.log
preprocessing:
  max_faces_per_image: 1
  num_workers: 1
  processing_type: detect_adjust_image
