"""Generate the FineFACE-recipe ANCHOR configs (baseline-positioning).

NOT one of the 5 attribution factors. Reproduces the FineFACE paper's
*training recipe* on a PLAIN ResNet-50 + Linear head (i.e., WITHOUT
their multi-expert architecture). Isolates "how much of the gap is
recipe vs head architecture". See docs/baseline_positioning.md §5.

Recipe extracted verbatim from FineFACE (Liu et al., 2024, §4.1):
  - Backbone: ResNet-50
  - Optimizer: SGD + momentum 0.9 + weight_decay 5e-4
  - LR diff: 2e-4 backbone, 2e-3 head (cosine annealing)
  - Batch size: 16
  - Input: 448x448 with RandomCrop padding=8
  - Normalize: (0.5, 0.5, 0.5)
  - Early stopping
  - Head: their multi-expert — REPLACED HERE by plain Linear

Everything else MATCHED with our protocol (clean dataset, 3 seeds,
criterion val_f1_macro, fp32, num_workers=0, 25 epochs).
"""

from __future__ import annotations

from pathlib import Path

import yaml

OUT_DIR = Path("configs/anchor_finefacerecipe")
SEEDS = [42, 1, 2]
CLEAN_CSV = "data/raw/fairface/fairface_labels_clean.csv"


def _cfg(seed: int) -> dict:
    return {
        "model": {
            "name": "LResNet50E_IR",
            "backbone_arch": "resnet50",  # FineFACE-paper backbone
            "pretrained": True,
            "num_classes": 7,
            "dropout": 0.2,
            "head": "linear",  # plain Linear (no multi-expert here)
            "arcface_s": 30.0,
            "arcface_m": 0.5,
            "arcface_easy_margin": False,
        },
        "training": {
            "batch_size": 16,  # FineFACE paper
            "learning_rate": 0.002,  # FineFACE head/classifier LR
            "lr_backbone": 0.0002,  # FineFACE backbone LR
            "weight_decay": 5e-4,  # FineFACE
            "num_epochs": 25,
            "optimizer": "sgd",  # FineFACE
            "scheduler": "cosineannealingwarmrestarts",
            "loss_function": "cross_entropy",
            "test_size": 0.1,
            "val_size": 0.1,
            "num_workers": 0,
            "random_state": seed,
            "grad_clip_norm": 5.0,
            "early_stopping_patience": 5,
            "use_amp": False,
            "train_random_crop_padding": 8,  # FineFACE: Resize+Crop pad=8
        },
        "image": {
            "image_size": [448, 448],  # FineFACE
            "image_mean": [0.5, 0.5, 0.5],  # FineFACE generic norm
            "image_std": [0.5, 0.5, 0.5],
        },
        "preprocessing": {
            "processing_type": "detect_adjust_image",
            "num_workers": 4,
            "rotate_angle": 45,
            "num_rotations": 8,
            "max_faces_per_image": 1,
        },
        "data": {
            "dataset_file": CLEAN_CSV,
            "dataset_image_input_path": "data/processed/fairface_aligned",
            "dataset_image_output_path": "data/processed/fairface_aligned",
            "balance": "undersample",
        },
        "bucket": {
            "function": "download",
            "bucket_client": "s3",
            "bucket_path_file": "data/raw/bucket/",
            "object_file_name": "fairface_original_images.zip",
            "bucket_name": "dataset-fairface",
        },
        "logging": {
            "log_dir": "outputs/logs",
            "log_level": "INFO",
            "format": "%(asctime)s [%(run_id)s] %(name)s %(levelname)s: %(message)s",
            "log_bucket_file": "bucket.log",
            "log_preprocessing_file": "preprocessing.log",
            "log_face_data_file": "face_data.log",
            "log_version_file": "version.log",
            "log_training_file": "training.log",
            "log_evaluation_file": "evaluation.log",
        },
    }


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    written = []
    for seed in SEEDS:
        cfg = _cfg(seed)
        fname = f"anchor_finefacerecipe_s{seed:02d}.yaml"
        header = (
            f"# FineFACE-recipe ANCHOR (NO multi-expert) — seed={seed}\n"
            f"# ResNet-50 + Linear + SGD diff-LR (bb=2e-4, head=2e-3) + 448px\n"
            f"# RandomCrop pad=8 + Normalize(0.5,0.5,0.5). Isolates 'how much\n"
            f"# of the FineFACE gap is recipe vs multi-expert head'.\n"
            f"# Generated by scripts/generate_anchor_finefacerecipe_configs.py.\n\n"
        )
        with open(OUT_DIR / fname, "w", encoding="utf-8") as f:
            f.write(header)
            yaml.safe_dump(cfg, f, sort_keys=False, default_flow_style=False)
        written.append(fname)

    print(f"Wrote {len(written)} configs to {OUT_DIR}:")
    for w in sorted(written):
        print(f"  {w}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
