"""Generate the Factor-3 (loss family) configs — AdaFace + MagFace.

Factor 3 isolates the loss-function contribution to demographic
disparity. Protocol identical to the dataset-factor batch: clean
dataset, ResNet-50 backbone, AdaFace/MagFace canonical margin head,
3 seeds (42,1,2), matched comparison basis, fp32, num_workers=0
(Windows deadlock-proof), 25 epochs, early stopping.

The control and references are NOT re-run — they already exist in the
dataset-factor batch under the SAME protocol/environment:
  - CE + linear  -> outputs/dataset_factor/exp_r2base_exp05_ce_s{42,01,02}
  - ArcFace      -> outputs/dataset_factor/exp_r2base_exp06_af_s{42,01,02}

This script emits only the 6 new runs:
  adaface s{42,01,02}, magface s{42,01,02}

Standing rule (memory): 3 seeds, matched basis, mean ± std; gains
within 1 sigma are non-significant.
"""

from __future__ import annotations

from pathlib import Path

import yaml

OUT_DIR = Path("configs/experiments_factor3")
SEEDS = [42, 1, 2]
CLEAN_CSV = "data/raw/fairface/fairface_labels_clean.csv"

# Each loss uses its canonical margin head. Defaults from the papers.
RECIPES = {
    "adaface": {"head": "adaface", "loss_function": "adaface"},
    "magface": {"head": "magface", "loss_function": "magface"},
}


def _cfg(head: str, loss: str, seed: int) -> dict:
    return {
        "model": {
            "name": "LResNet50E_IR",
            "pretrained": True,
            "num_classes": 7,
            "dropout": 0.2,
            "head": head,
            "arcface_s": 30.0,
            "arcface_m": 0.5,
            "arcface_easy_margin": False,
            # AdaFace (paper defaults)
            "adaface_m": 0.4,
            "adaface_h": 0.333,
            # MagFace (paper defaults; regulariser off so the loss stays
            # CE-on-margin-logits, matched with ArcFace in the factor study)
            "magface_l_a": 10.0,
            "magface_u_a": 110.0,
            "magface_l_m": 0.45,
            "magface_u_m": 0.8,
            "magface_lambda_g": 0.0,
        },
        "training": {
            "batch_size": 128,
            "learning_rate": 0.001,
            "num_epochs": 25,
            "optimizer": "adamw",
            "scheduler": "cosineannealingwarmrestarts",
            "loss_function": loss,
            "test_size": 0.1,
            "val_size": 0.1,
            "num_workers": 0,  # Windows deadlock-proof (matched w/ dataset_factor)
            "random_state": seed,
            "grad_clip_norm": 5.0,
            "early_stopping_patience": 5,
            "use_amp": False,  # fp32 — matched with the dataset-factor batch
        },
        "image": {
            "image_size": [224, 224],
            "image_mean": [0.485, 0.456, 0.406],
            "image_std": [0.229, 0.224, 0.225],
        },
        "preprocessing": {
            "processing_type": "detect_adjust_image",
            "num_workers": 4,
            "rotate_angle": 45,
            "num_rotations": 8,
            "max_faces_per_image": 1,
        },
        "data": {
            "dataset_file": CLEAN_CSV,
            "dataset_image_input_path": "data/processed/fairface_aligned",
            "dataset_image_output_path": "data/processed/fairface_aligned",
            "balance": "undersample",
        },
        "bucket": {
            "function": "download",
            "bucket_client": "s3",
            "bucket_path_file": "data/raw/bucket/",
            "object_file_name": "fairface_original_images.zip",
            "bucket_name": "dataset-fairface",
        },
        "logging": {
            "log_dir": "outputs/logs",
            "log_level": "INFO",
            "format": "%(asctime)s [%(run_id)s] %(name)s %(levelname)s: %(message)s",
            "log_bucket_file": "bucket.log",
            "log_preprocessing_file": "preprocessing.log",
            "log_face_data_file": "face_data.log",
            "log_version_file": "version.log",
            "log_training_file": "training.log",
            "log_evaluation_file": "evaluation.log",
        },
    }


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    written = []
    for rkey, r in RECIPES.items():
        for seed in SEEDS:
            cfg = _cfg(r["head"], r["loss_function"], seed)
            fname = f"exp_f3_{rkey}_s{seed:02d}.yaml"
            header = (
                f"# Factor 3 (loss family) — {rkey} seed={seed}\n"
                f"# clean dataset, ResNet-50, {rkey} margin head, 25ep, fp32,\n"
                f"# num_workers=0, 3-seed matched protocol.\n"
                f"# Control/reference (NOT re-run): CE+linear and ArcFace from\n"
                f"# the dataset-factor batch (outputs/dataset_factor/exp_r2base_*).\n"
                f"# Generated by scripts/generate_factor3_configs.py.\n\n"
            )
            with open(OUT_DIR / fname, "w", encoding="utf-8") as f:
                f.write(header)
                yaml.safe_dump(cfg, f, sort_keys=False, default_flow_style=False)
            written.append(fname)

    print(f"Wrote {len(written)} configs to {OUT_DIR}:")
    for w in sorted(written):
        print(f"  {w}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
