"""Generate the Factor-4 (learning paradigm) configs — canonical SupCon.

Factor 4 isolates the contribution of the *contrastive paradigm* to
demographic disparity. One-stage joint: total loss = CE(linear head) +
lambda * SupCon(projection) — same backbone / data / eval head /
criterion as every other factor (matched basis). SupCon is canonical
(no fairness modification); FSCL/FairCL are SOTA *mitigation* cited as
related work, not the factor arm. See docs/sota_pdf_synthesis.md §2.1.

Protocol identical to the loss/dataset factors: clean dataset,
ResNet-50 ImageNet, linear head, 3 seeds (42,1,2), matched basis,
fp32, num_workers=0 (Windows deadlock-proof), 25 epochs, early stopping
on val_f1_macro (inherited default — the corrected criterion).

Control is NOT re-run — CE+linear (no contrastive term) already exists
under the SAME protocol/criterion in the definitive baseline:
  outputs/definitive/baseline/exp_r2base_exp05_ce_s{42,01,02}

This script emits only the 3 new runs: supcon s{42,01,02}.
"""

from __future__ import annotations

from pathlib import Path

import yaml

OUT_DIR = Path("configs/experiments_factor4")
SEEDS = [42, 1, 2]
CLEAN_CSV = "data/raw/fairface/fairface_labels_clean.csv"


def _cfg(seed: int) -> dict:
    return {
        "model": {
            "name": "LResNet50E_IR",  # alias of ResNet50ImageNet (mlflow tag)
            "pretrained": True,
            "num_classes": 7,
            "dropout": 0.2,
            "head": "linear",  # matched control head; paradigm is the factor
            "arcface_s": 30.0,
            "arcface_m": 0.5,
            "arcface_easy_margin": False,
        },
        "training": {
            "batch_size": 128,
            "learning_rate": 0.001,
            "num_epochs": 25,
            "optimizer": "adamw",
            "scheduler": "cosineannealingwarmrestarts",
            "loss_function": "cross_entropy",
            "test_size": 0.1,
            "val_size": 0.1,
            "num_workers": 0,  # Windows deadlock-proof (matched)
            "random_state": seed,
            "grad_clip_norm": 5.0,
            "early_stopping_patience": 5,
            "use_amp": False,  # fp32 — matched with the other factors
            # checkpoint_metric omitted -> inherits val_f1_macro (the
            # corrected criterion; see docs/checkpoint_criterion_audit.md)
            "contrastive": {
                "enabled": True,
                "method": "supcon",
                "temperature": 0.07,  # SupCon paper default
                "lambda_weight": 0.5,  # CE + 0.5 * SupCon (joint)
                "proj_dim": 128,
                "proj_hidden": 512,
            },
        },
        "image": {
            "image_size": [224, 224],
            "image_mean": [0.485, 0.456, 0.406],
            "image_std": [0.229, 0.224, 0.225],
        },
        "preprocessing": {
            "processing_type": "detect_adjust_image",
            "num_workers": 4,
            "rotate_angle": 45,
            "num_rotations": 8,
            "max_faces_per_image": 1,
        },
        "data": {
            "dataset_file": CLEAN_CSV,
            "dataset_image_input_path": "data/processed/fairface_aligned",
            "dataset_image_output_path": "data/processed/fairface_aligned",
            "balance": "undersample",
        },
        "bucket": {
            "function": "download",
            "bucket_client": "s3",
            "bucket_path_file": "data/raw/bucket/",
            "object_file_name": "fairface_original_images.zip",
            "bucket_name": "dataset-fairface",
        },
        "logging": {
            "log_dir": "outputs/logs",
            "log_level": "INFO",
            "format": "%(asctime)s [%(run_id)s] %(name)s %(levelname)s: %(message)s",
            "log_bucket_file": "bucket.log",
            "log_preprocessing_file": "preprocessing.log",
            "log_face_data_file": "face_data.log",
            "log_version_file": "version.log",
            "log_training_file": "training.log",
            "log_evaluation_file": "evaluation.log",
        },
    }


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    written = []
    for seed in SEEDS:
        cfg = _cfg(seed)
        fname = f"exp_f4_supcon_s{seed:02d}.yaml"
        header = (
            f"# Factor 4 (learning paradigm) — canonical SupCon seed={seed}\n"
            f"# clean dataset, ResNet-50 ImageNet, linear head + CE + 0.5*SupCon\n"
            f"# (one-stage joint), 25ep, fp32, num_workers=0, criterion=val_f1_macro,\n"
            f"# 3-seed matched protocol. Control (NOT re-run): CE+linear from the\n"
            f"# definitive baseline (outputs/definitive/baseline/exp_r2base_exp05_ce_*).\n"
            f"# Generated by scripts/generate_factor4_configs.py.\n\n"
        )
        with open(OUT_DIR / fname, "w", encoding="utf-8") as f:
            f.write(header)
            yaml.safe_dump(cfg, f, sort_keys=False, default_flow_style=False)
        written.append(fname)

    print(f"Wrote {len(written)} configs to {OUT_DIR}:")
    for w in sorted(written):
        print(f"  {w}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
